service:
  name: tweets-service

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:APOLLO_SERVER_AWS_REGION, us-east-1}
  stage: ${opt:stage, dev}
  # environment:
  #   NODE_ENV: ${env:NODE_ENV, "development"}
  #   SERVERLESS_STAGE: ${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  tweets:
    handler: src/index.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true

custom:
  webpack:
    webpackConfig: ./config/webpack.config.js
    includeModules: true
  serverless-offline:
    port: ${env:APOLLO_SERVER_PORT, 4001}
